apiVersion: v1
kind: Pod
metadata:
  name: nodecellar
spec:
  restartPolicy: Never
  containers:
  - name: nodecellar
    image: dfilppi/nodecellar:v1
    workingDir: /root/nodecellar-master
    command: ["../node/bin/node","server.js"]
    ports:
    - containerPort: 3000
      hostPort: 3000
      hostIP: { get_property: [ master, ip]}
    env:
    - name: MONGO_HOST
      value: { get_input: host_ip }
    - name: MONGO_PORT
      value: { concat: ["", { get_property: [ mongod1 , port ]}] }
