# -*- mode: ruby -*-
# vi: set ft=ruby :


Vagrant.configure("2") do |config|
 config.vm.define :kub do |kub_config|
   kub_config.vm.box = "ubuntu/trusty64"
   kub_config.vm.network :private_network, ip: "192.168.33.10"
   kub_config.vm.provider "virtualbox" do |vb|
     vb.customize ["modifyvm", :id, "--memory", "2000"]
   end
 end
 config.vm.define :mongo do |m_config|
   m_config.vm.box = "ubuntu/trusty64"
   m_config.vm.network :private_network, ip: "192.168.33.11"
   m_config.vm.provider "virtualbox" do |vb|
     vb.customize ["modifyvm", :id, "--memory", "3000"]
   end
 end
end

